version: '3.8'

services:
  app:
    container_name: web_scandiweb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    restart: unless-stopped
  
  nginx:
    container_name: nginx_scandiweb
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped

  mysql:
    container_name: mysql_scandiweb
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: scandiweb
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: unless-stopped